// <auto-generated />
using System;
using DPXQRPoc.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DPXQRPoc.Data.Migrations
{
    [DbContext(typeof(DPXPocDbContext))]
    partial class DPXPocDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DPXQRPoc.Data.DataModels.IsoTimestamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EventSource")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("FileGuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PaymentGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("PaymentInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("IsoTimestamps", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
